services: 
  sonic:
    image: valeriansaliou/sonic:v1.4.9 # Using a specific version
    container_name: sonic_search_engine
    ports:
      - "1491:1491" # Host:Container
    environment:
      - SONIC_PASSWORD=SecretPassword
    volumes:
      - ./sonic.cfg:/etc/sonic.cfg # Corrected path to /etc/sonic.cfg
      - sonic_data_volume:/var/lib/sonic/store/ # Use a named volume for Sonic data
    restart: unless-stopped
  app:
    build: .
    container_name: let_shopping_app
    ports:
      - "3030:3000"    
    depends_on:
      - sonic # Chỉ phụ thuộc vào sonic, MongoDB chạy riêng
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/let_shopping
      - SONIC_HOST=sonic
      - SONIC_PORT=1491
      - SONIC_AUTH=SecretPassword
    restart: unless-stopped

volumes:
  # mongodb_data:
  # sonic_data_volume: {}