apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: main-app
  name: main-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
            - name: SONIC_GRPC_ENDPOINT
              value: sonic-server:50051
          image: nieltran/main-app:v1.0
          imagePullPolicy: Always
          name: main-app
          ports:
            - containerPort: 3030
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: main-app
  annotations:
    nginx-lb.kubernetes.io/external-lb: "ingress-only"
    nginx-lb.kubernetes.io/backend-protocol: "HTTP"
spec:
  type: ClusterIP
  selector:
    app: main-app
  ports:
  - protocol: TCP
    port: 80 # The port to expose internally
    targetPort: 3030 # The port main-app is listening on inside the container
    name: http
---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: main-app-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: main-app-deployment
#   minReplicas: 2
#   maxReplicas: 5
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 70
# ---
# apiVersion: policy/v1
# kind: PodDisruptionBudget
# metadata:
#   name: main-app-pdb
# spec:
#   minAvailable: 2
#   selector:
#     matchLabels:
#       app: main-app